import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import Navbar from "@/components/navbar";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Habit Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const user = await db.user.findFirst();
   return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background text-foreground">
         <ThemeProvider
          attribute="class"
          defaultTheme="system" // Use fixed default instead of system
          enableSystem // Disable system theme detection
          disableTransitionOnChange
        >
          <SessionProvider>
            <div className="relative">
            <Navbar />
            <main id="main-content">{children}</main>
            </div>
            </SessionProvider>  
        </ThemeProvider>  
      </body>
    </html>
  );
}
